Add Webp support
stephenmoloney/fastimage pull request #25
Opened 2018-10-02 18:24 UTC by sneako

Hi and thanks for the lib!

I needed webp support, so I ported the Ruby implementation from: https://github.com/sdsykes/fastimage/blob/master/lib/fastimage.rb#L591

Let me know what you think

2018-10-02 18:33 UTC, sneako commented on test/fastimage_test.exs
> +  @webp_vp8x_url "https://raw.githubusercontent.com/sdsykes/fastimage/master/test/fixtures/webp_vp8x.webp"
we can point these urls at this repo, but left them as is so you could see the tests pass first

2018-10-02 20:38 UTC, stephenmoloney commented
Hey @sneako, thanks for the PR. Webp support is a good addition.
I don't use bitwise operators much so I'll rely on you for that part.

2018-10-02 20:59 UTC, sneako commented
@stephenmoloney glad you like the feature. Honestly, I do not use bitwise operators much either, but it was easy to translate from the ruby code and passes the tests. I'm surprised to see test coverage has decreased, when i run the tests on master, it reports 61.4%, so I thought coverage increased. I'll update the urls to point at this repo now. Is there anything else you would like me to change before merging?

2018-10-02 21:00 UTC, stephenmoloney requested changes
I think this looks good to merge.

The main thing is to clarify 

- You are the owner of the images and are releasing them under the project `MIT` license 
- Change the http url for the images as discussed in the review

Thanks !

2018-10-02 21:00 UTC, stephenmoloney commented on bench/fastimage_bench.exs
> +  @webp_vp8_file "./priv/test_vp8.webp"
Are these images (./priv/test_*.webp) taken by you and owned by you ? [just to avoid any potential copyright issue]

2018-10-02 21:00 UTC, stephenmoloney commented on test/fastimage_test.exs
> +  defp list(n) do
Nice addition

2018-10-02 21:00 UTC, stephenmoloney commented on test/fastimage_test.exs
> +  @webp_vp8_expected_size %Fastimage.Dimensions{width: 550, height: 368}
Now that there are multiple sizes, `@expected_size` on it's own is a little bit more confusing. Not sure of what alternative though.

2018-10-02 21:00 UTC, stephenmoloney commented on test/fastimage_test.exs
> +  @webp_vp8x_url "https://raw.githubusercontent.com/sdsykes/fastimage/master/test/fixtures/webp_vp8x.webp"
Let's use `https://raw.githubusercontent.com/stephenmoloney/fastimage/master/priv/webp_*.webp` instead.

2018-10-02 21:00 UTC, stephenmoloney commented on test/fastimage_test.exs
> +  @webp_vp8x_url "https://raw.githubusercontent.com/sdsykes/fastimage/master/test/fixtures/webp_vp8x.webp"
and thanks for pointing that out BTW.

2018-10-02 21:07 UTC, sneako commented on bench/fastimage_bench.exs
> +  @webp_vp8_file "./priv/test_vp8.webp"
These images were all taken from the test suite of the Ruby gem FastImage, which also has an MIT license https://github.com/sdsykes/fastimage/blob/master/MIT-LICENSE
So we should be ok to use them as well, right?

2018-10-02 21:11 UTC, sneako commented on test/fastimage_test.exs
> +  @webp_vp8_expected_size %Fastimage.Dimensions{width: 550, height: 368}
I know what you mean. Maybe something like `standard_expected_size`? It's just a tad bit less ambiguous

2018-10-02 21:23 UTC, stephenmoloney commented on test/fastimage_test.exs
> +  @webp_vp8_expected_size %Fastimage.Dimensions{width: 550, height: 368}
What might be cleaner is to just create the `test_vp*.webp` images using the same one as already in this lib and then fix it to `@expected_size` for consistency and drop the external image from sdykes lib. I just need to figure out how to create the three different webp formats.

2018-10-02 21:25 UTC, stephenmoloney commented
Also, need to add a small mention of support for webp [here](https://github.com/stephenmoloney/fastimage#features)

2018-10-02 21:55 UTC, sneako commented on test/fastimage_test.exs
> +  @webp_vp8_expected_size %Fastimage.Dimensions{width: 550, height: 368}
I used https://developers.google.com/speed/webp/docs/cwebp to resize the images to match the `expected_size`. I made sure that the tool did not change the type of webp (vp8*) of each new file.

2018-10-02 22:35 UTC, sneako commented
@stephenmoloney I noticed there were actually several places that had the full list of supported types, and the options docs were repeated too so I did some consolidation. What do you think?

2018-10-03 08:52 UTC, stephenmoloney commented on bench/fastimage_bench.exs
> +  @webp_vp8_file "./priv/test_vp8.webp"
I found that image on [Google's webp site](https://developers.google.com/speed/webp/gallery1#image_credits), seems they got it from somewhere else after seeking permission and giving credit which is the correct etiquette for this project too if we use it (which is a possibility)

2018-10-03 09:15 UTC, stephenmoloney commented on lib/fastimage.ex
> +          max_error_retries: non_neg_integer
meant to be `max_redirect_retries`

2018-10-03 09:26 UTC, stephenmoloney commented on test/fastimage_test.exs
>    @tag :jpeg
Not sure why I put this tag here, I think we can remove this and use the same `assert_size_and_type/3` function inside this test for consistency

2018-10-03 11:29 UTC, stephenmoloney commented on test/fastimage_test.exs
>    @tag :jpeg
I fixed that.

2018-10-03 11:30 UTC, stephenmoloney commented on lib/fastimage.ex
> +          max_error_retries: non_neg_integer
I fixed this too.

2018-10-03 11:32 UTC, stephenmoloney commented
@sneako 

I have made a few changes on top of your branch.

Would you mind merging this branch `feature/webp` into your branch in this PR ?

Thanks !

2018-10-03 12:05 UTC, sneako commented
Thanks for taking care of those updates!

2018-10-03 12:36 UTC, stephenmoloney commented
:+1: :tada:

2018-10-03 12:36 UTC, merged